Changes for PowerAPI monitoring

diff --git a/.github/workflows/translations.yml b/.github/workflows/translations.yml
--- a/.github/workflows/translations.yml
+++ b/.github/workflows/translations.yml
@@ -1,78 +1,39 @@
-#
-# Logisim-evolution translation files (*.properties) checker.
-#
-# Github action that ensures project translation files are in sync and
-# in a good shape in general.
-#
-# Worker uses trans-tool: https://github.com/MarcinOrlowski/trans-tool
-#
-# Marcin Orlowski
-#
-
-name: "Translations"
-
-on:
-  push:
-    branches: [ main ]
-  pull_request:
-    branches: [ main ]
-
 jobs:
   translations_lint:
-    name: "Translations linter"
-    runs-on: ubuntu-latest
-
+    name: Translations linter
+    runs-on: self-hosted
     steps:
-      # https://github.com/marketplace/actions/checkout
-      - name: "Checkout sources"
-        uses: actions/checkout@v4
-
-      # https://github.com/marketplace/actions/paths-changes-filter
-      - name: "Looking for modified files..."
-        uses: dorny/paths-filter@v3
-        id: filter
-        with:
-          filters: |
-            translations:
-              - 'src/main/resources/resources/logisim/**/*.properties'
-
-      - name: "===> SEE HERE FOR LINTING REPORT"
-        if: steps.filter.outputs.translations == 'true'
-        run: |
-          # Have no mercy.
-          set -euo pipefail
-
-          sudo pip install pysimple-log==0.0.5 trans-tool==2.5.2
-          trans-tool --version
-
-          # Declare constants
-          declare -r resources_path="src/main/resources/resources/logisim/"
-          declare -r base_language="en"
-
-          # Get all Logisim's localization base (EN) files
-          declare -r base_files=$(find ${resources_path}* -name "*.properties" | grep -E '*/[a-zA-Z]+.properties$' | grep -v settings.properties)
-
-          # Read currently supported languages from settings.properties
-          declare -r langs="$(cut -d  ' ' -f3- < "${resources_path}settings.properties")"
-
-          # Validate.
-          failed=
-          for file in ${base_files}; do
-            # Keep validating even if previous run failed, so we can have complete report.
-            trans-tool -l "${langs}" -ls "${base_language}" -b "${file}" >> /tmp/report.txt || failed="YES"
-          done
-
-          if [[ "${failed}" == "YES" ]]; then
-            echo ""
-            echo "Project *.properties files have some problems or are out of sync."
-            echo "Please see 'Update existing translations' in trans-tool's docs:"
-            echo "  https://github.com/MarcinOrlowski/trans-tool"
-            echo "for more info on how to address these issues."
-            echo ""
-            cat /tmp/report.txt
-            echo ""
-
-            # Do not fail the action no matter what. This is intentional
-            # unless translation files are in better condition.
-            # exit 1
-          fi
+    - continue-on-error: true
+      name: Checkout sources
+      uses: actions/checkout@v4
+    - continue-on-error: true
+      id: filter
+      name: Looking for modified files...
+      uses: dorny/paths-filter@v3
+      with:
+        filters: "translations:\n  - 'src/main/resources/resources/logisim/**/*.properties'\n"
+    - continue-on-error: true
+      if: steps.filter.outputs.translations == 'true'
+      name: ===> SEE HERE FOR LINTING REPORT
+      run: "# Have no mercy.\nset -euo pipefail\n\nsudo pip install pysimple-log==0.0.5\
+        \ trans-tool==2.5.2\ntrans-tool --version\n\n# Declare constants\ndeclare\
+        \ -r resources_path=\"src/main/resources/resources/logisim/\"\ndeclare -r\
+        \ base_language=\"en\"\n\n# Get all Logisim's localization base (EN) files\n\
+        declare -r base_files=$(find ${resources_path}* -name \"*.properties\" | grep\
+        \ -E '*/[a-zA-Z]+.properties$' | grep -v settings.properties)\n\n# Read currently\
+        \ supported languages from settings.properties\ndeclare -r langs=\"$(cut -d\
+        \  ' ' -f3- < \"${resources_path}settings.properties\")\"\n\n# Validate.\n\
+        failed=\nfor file in ${base_files}; do\n  # Keep validating even if previous\
+        \ run failed, so we can have complete report.\n  trans-tool -l \"${langs}\"\
+        \ -ls \"${base_language}\" -b \"${file}\" >> /tmp/report.txt || failed=\"\
+        YES\"\ndone\n\nif [[ \"${failed}\" == \"YES\" ]]; then\n  echo \"\"\n  echo\
+        \ \"Project *.properties files have some problems or are out of sync.\"\n\
+        \  echo \"Please see 'Update existing translations' in trans-tool's docs:\"\
+        \n  echo \"  https://github.com/MarcinOrlowski/trans-tool\"\n  echo \"for\
+        \ more info on how to address these issues.\"\n  echo \"\"\n  cat /tmp/report.txt\n\
+        \  echo \"\"\n\n  # Do not fail the action no matter what. This is intentional\n\
+        \  # unless translation files are in better condition.\n  # exit 1\nfi\n"
+name: Translations
+on:
+  repository_dispatch:
+    types: trigger-ga___translations.yml
